name: task_manager_app
description: "Task Manager App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.0
  shared_preferences: ^2.1.1
  google_fonts: 6.1.0
  easy_localization: ^3.0.5
  go_router: ^13.0.0
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
